# Generated by Django 5.2.8 on 2025-11-26 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='visa/country/covers/')),
                ('flag_image', models.ImageField(blank=True, null=True, upload_to='visa/country/flags/')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='CountryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_subtitle', models.TextField(blank=True, null=True)),
                ('overview_title', models.CharField(blank=True, max_length=255, null=True)),
                ('overview_content', models.TextField(blank=True, null=True)),
                ('visa_types_summary', models.CharField(blank=True, help_text='Ví dụ: Visa du lịch, thăm thân, công tác', max_length=255, null=True)),
                ('visa_processing_time', models.CharField(blank=True, help_text='Ví dụ: 10–30 ngày', max_length=255, null=True)),
                ('visa_highlight_note_1', models.CharField(blank=True, max_length=255, null=True)),
                ('visa_highlight_note_2', models.CharField(blank=True, max_length=255, null=True)),
                ('visa_highlight_note_3', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_featured_requirement_1', models.TextField(blank=True, null=True)),
                ('cta_featured_requirement_2', models.TextField(blank=True, null=True)),
                ('cta_featured_requirement_3', models.TextField(blank=True, null=True)),
                ('cta_featured_requirement_4', models.TextField(blank=True, null=True)),
                ('cta_subtitle', models.TextField(blank=True, null=True)),
                ('cta_button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='visa.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountrySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='visa/country/sections/')),
                ('image_left', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='visa.country')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CountryTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tip_type', models.CharField(choices=[('risk', 'Rủi ro bị từ chối'), ('tip', 'Mẹo tăng tỉ lệ đậu')], max_length=20)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='visa.country')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('purpose', models.CharField(choices=[('family_visit', 'Thăm người thân'), ('tourism', 'Du lịch'), ('business', 'Công tác'), ('student', 'Du học'), ('work', 'Lao động'), ('other', 'Khác')], default='other', max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_types', to='visa.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='visa.country')),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='visa.visatype')),
            ],
            options={
                'verbose_name': 'Required Document',
                'verbose_name_plural': 'Required Documents',
                'unique_together': {('country', 'visa_type', 'name')},
            },
        ),
    ]
