# Generated by Django 5.2.8 on 2025-12-02 07:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Quốc gia', 'verbose_name_plural': 'Quốc gia'},
        ),
        migrations.AlterModelOptions(
            name='countrydetail',
            options={'verbose_name': 'Giới thiệu từng nước', 'verbose_name_plural': 'Giới thiệu từng nước'},
        ),
        migrations.AlterModelOptions(
            name='countrysection',
            options={'ordering': ['order'], 'verbose_name': 'Các phần trang giới thiệu', 'verbose_name_plural': 'Các phần trang giới thiệu'},
        ),
        migrations.AlterModelOptions(
            name='countrytip',
            options={'ordering': ['order'], 'verbose_name': 'Tip', 'verbose_name_plural': 'Tips'},
        ),
        migrations.AlterModelOptions(
            name='requireddocument',
            options={'verbose_name': 'Yêu cầu hồ sơ', 'verbose_name_plural': 'Yêu cầu hồ sơ'},
        ),
        migrations.AlterModelOptions(
            name='visatype',
            options={'verbose_name': 'Loại visa', 'verbose_name_plural': 'Loại visa'},
        ),
        migrations.AlterField(
            model_name='countrydetail',
            name='cta_featured_requirement_1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrydetail',
            name='cta_featured_requirement_2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrydetail',
            name='cta_featured_requirement_3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrydetail',
            name='cta_featured_requirement_4',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrydetail',
            name='cta_subtitle',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrydetail',
            name='hero_subtitle',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrydetail',
            name='overview_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrysection',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='countrytip',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visatype',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
