# Generated by Django 5.2.8 on 2025-12-02 07:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Danh mục bài viết', 'verbose_name_plural': 'Danh mục bài viết'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Danh sách bài viết', 'verbose_name_plural': 'Danh sách bài viết'},
        ),
        migrations.AlterModelOptions(
            name='blogtag',
            options={'verbose_name': 'Tags bài viết', 'verbose_name_plural': 'Tags bài viết'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
