# Generated by Django 5.2.8 on 2025-11-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Ảnh đại diện của trang', null=True, upload_to='pages/')),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
