# Generated by Django 5.2.8 on 2025-11-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.URLField(blank=True)),
                ('logo', models.ImageField(upload_to='company/')),
                ('hotline', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('google_map', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('zalo', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('normal_working_time', models.TextField(blank=True, help_text="Nhập giờ làm việc, ví dụ: '08:00-17:00'")),
                ('saturday_working_time', models.TextField(blank=True, help_text="Nhập giờ làm việc, ví dụ: '08:00-17:00'")),
                ('web_dev_partner', models.CharField(max_length=255)),
                ('partner_web_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
    ]
