# Generated by Django 5.2.8 on 2025-12-02 07:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='normal_working_time',
            field=models.CharField(blank=True, help_text="Nhập giờ làm việc, ví dụ: '08:00-17:00'"),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='saturday_working_time',
            field=models.CharField(blank=True, help_text="Nhập giờ làm việc, ví dụ: '08:00-17:00'"),
        ),
    ]
