# Generated by Django 5.2.8 on 2025-11-26 01:42

import apps.clients.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solo_or_group_travel', models.CharField(choices=[('solo', 'Đi một mình'), ('group', 'Đi theo nhóm / gia đình')], default='solo', max_length=20, verbose_name='Đi một mình hay theo nhóm')),
                ('travel_history_countries', models.CharField(blank=True, max_length=255, null=True)),
                ('family_members', models.TextField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, choices=[('business_owner', 'Chủ DN / Tự doanh'), ('employee', 'Nhân viên công ty'), ('freelance', 'Lao động tự do'), ('retired', 'Đã nghỉ hưu'), ('homemaker', 'Nội trợ'), ('student', 'Sinh viên'), ('pupil', 'Học sinh'), ('other', 'Khác')], max_length=50, null=True)),
                ('inviter_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('inviter_dob', models.DateField(blank=True, null=True)),
                ('inviter_address', models.CharField(blank=True, max_length=500, null=True)),
                ('inviter_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('inviter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('visa_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visa.visatype')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='clients.client')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(choices=[('passport', 'Hộ chiếu'), ('id_card', 'CCCD'), ('invitation', 'Thư mời'), ('financial', 'Giấy tờ tài chính'), ('personal', 'Giấy tờ cá nhân'), ('other', 'Giấy tờ khác')], max_length=50)),
                ('file', models.FileField(upload_to=apps.clients.utils.application_file_upload_path)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clients.application')),
            ],
            options={
                'verbose_name': 'Application File',
                'verbose_name_plural': 'Application Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
