# Generated by Django 5.2.8 on 2025-12-02 07:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đăng ký dịch vụ', 'verbose_name_plural': 'Đăng ký dịch vụ'},
        ),
        migrations.AlterModelOptions(
            name='applicationfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'File khách hàng gửi', 'verbose_name_plural': 'File khách hàng gửi'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Danh sách khách hàng', 'verbose_name_plural': 'Danh sách khách hàng'},
        ),
        migrations.AlterField(
            model_name='application',
            name='family_members',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
