# Generated by Django 5.2.8 on 2025-12-02 07:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'verbose_name': 'Danh mục FAQ', 'verbose_name_plural': 'Danh mục FAQ'},
        ),
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['order'], 'verbose_name': 'Danh sách FAQ', 'verbose_name_plural': 'Danh sách FAQ'},
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
